  
version: "3"
services:
  gateway:
    image: gateway
    ports:
      - "8762:8762"
    networks:
      - test
    depends_on:
      - eureka

  eureka:
    image: eureka-server
    ports:
      - "8761:8761"
    networks:
      - test

  book-catalog:
    image: book-catalog
    ports:
      - "8686:8686"
    networks:
      - test

  postsql:
    image: postgres:alpine
    ports:
      - "5432:5555"
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - test

  book-service:
    image: book-service
    ports:
      - "8989:8989"
    networks:
      - test
    depends_on:
      - postsql

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - test
      
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    expose:
    - "9092"  
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 1
    networks:
      - test

  order-service:
    image: order-service
    ports:
      - "8786:8786"
    networks:
      - test
    depends_on:
      - zookeeper
      - kafka

  order-process:
    image: process-service
    ports:
      - "8685:8685"
    networks:
      - test
    depends_on:
      - zookeeper
      - kafka
      - mongo2

  reviewer-service:
    image: reviewer-service
    ports:
      - "8004:8004"
    networks:
      - test
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - test

  mongo2:
    image: mongo:latest
    command: mongod --port 27018
    ports:
      - "27018:27018"
    networks:
      - test

networks:
  test: